#!/bin/bash

BRANCH=`git rev-parse --symbolic --abbrev-ref $1`
if [ -z "$JENKINS" ]
then
    JENKINS=`docker inspect jenkins -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}'`
fi
# http://localhost:8080/git/notifyCommit?url=host.docker.internal:/Users/benhunter/local-work/dot-net-webinar/repo/dotnetapp
# how to program this? Also, putting an env variable for git repo in jenkins job means hitting 
# api endpoint requires you to use the literal variable. Not ideal.
# REPO_PATH=host.docker.internal:/Users/benhunter/local-work/dot-net-webinar/repo/dotnetapp
echo pushing to Jenkins server: $JENKINS
echo Update pushed to branch $BRANCH

curl $JENKINS:8080/git/notifyCommit?url='$REPO_PATH'&branches=$BRANCH
