apiVersion: v1
kind: Service
metadata:
    name: dotnetapp-${ENV}
    labels:
        app: dotnetapp
        env: ${ENV}
spec:
    type: NodePort
    ports:
        - port: 8080
    selector:
        app: dotnetapp
        env: ${ENV}

